env:
  SAUCECTL_LABEL: "$BUILDKITE_BUILD_NUMBER $BUILDKITE_PIPELINE_SLUG $BUILDKITE_BRANCH $BUILDKITE_COMMIT"
steps:
- agents: [queue=default-beta]
  command: ./.buildkite/publish.sh
  label: Build AARs and APKs
  plugins:
    - artifacts#v1.3.0:
        upload:
          - "MuxKalturaSDK/build/outputs/aar/*.aar"
          - "MuxKalturaSDK/build/outputs/logs/*.txt"
          - "automatedtests/build/outputs/apk/*/*.apk"
          - "automatedtests/build/outputs/apk/*/*/*.apk"
- wait
- agents: [queue=default-beta]
  command: docker run --rm -v $(pwd):/data -e BUILD_LABEL="$SAUCECTL_LABEL" -e TEST_APK=/data/automatedtests/build/outputs/apk/androidTest/debug/automatedtests-debug-androidTest.apk -e APP_APK=/data/automatedtests/build/outputs/apk/debug/automatedtests-debug.apk -e TEST_DEVICES='Google Pixel[ 345]*' -e SAUCE_USERNAME='mux-sauce' -e SAUCE_ACCESS_KEY=$$SAUCE_ACCESS_KEY muxinc/saucectl-runner:0.54.0-22f296b
  label: Test the Android Mux Stats Kaltura SDK
  retry:
    automatic:
      - exit_status: 1
        limit: 2
  plugins:
    - artifacts#v1.3.0:
        download:
          - "automatedtests/build/outputs/apk/debug/automatedtests-debug.apk"
          - "automatedtests/build/outputs/apk/androidTest/debug/automatedtests-debug-androidTest.apk"
- wait
- block: ":rocket: Deploy and release!"
  blocked_state: failed
  branches: "master"
- wait
- agents: [queue=default-beta]
  command: ./.buildkite/deploy.sh
  label: Deploy artifacts to release maven if it all worked
  branches: "master"
